#!/usr/bin/env python3
"""
Generate application files from templates.
Replaces multiple sed commands with a single Python script.
"""

import argparse
import json
import re
import sys
from pathlib import Path


class GenerationError(Exception):
    """Raised when file generation fails."""
    pass


def replace_placeholders(content: str, replacements: dict) -> str:
    """Replace {{PLACEHOLDER}} with values."""
    for key, value in replacements.items():
        content = content.replace(f"{{{{{key}}}}}", value)
    return content


def validate_no_unresolved_placeholders(content: str, file_name: str) -> None:
    """Fail fast if any {{PLACEHOLDER}} remains unresolved."""
    unresolved = re.findall(r'\{\{([A-Z_][A-Z0-9_]*)\}\}', content)
    if unresolved:
        raise GenerationError(
            f"Unresolved placeholders in {file_name}: {', '.join(set(unresolved))}"
        )


def generate_from_template(
    template_path: str,
    output_path: str,
    replacements: dict,
    dry_run: bool = False
) -> str:
    """Generate a file from template with placeholder replacement."""
    with open(template_path, 'r') as f:
        content = f.read()

    result = replace_placeholders(content, replacements)
    validate_no_unresolved_placeholders(result, output_path)

    if dry_run:
        print(f"[DRY-RUN] Would generate {output_path}")
    else:
        with open(output_path, 'w') as f:
            f.write(result)
        print(f"Generated {output_path}")

    return result


def generate_setup_sql(
    template_path: str,
    migrations_sql_path: str,
    migrations_manifest_path: str,
    output_path: str,
    dry_run: bool = False
) -> None:
    """Generate setup.sql from template with migrations SQL."""
    # Read migrations SQL generated by generate_migrations_sql.py
    if not Path(migrations_sql_path).exists():
        raise GenerationError(
            f"Migrations SQL file not found: {migrations_sql_path}\n"
            "Run 'python scripts/generate/generate_migrations_sql.py' first to generate it."
        )

    # Read migrations manifest for metadata
    if not Path(migrations_manifest_path).exists():
        raise GenerationError(
            f"Migrations manifest not found: {migrations_manifest_path}\n"
            "Run 'python scripts/generate/generate_migrations_sql.py' first to generate it."
        )

    with open(migrations_sql_path, 'r') as f:
        migrations_sql = f.read()

    with open(migrations_manifest_path, 'r') as f:
        manifest = json.load(f)

    migrations_count = len(manifest.get('migrations', []))
    latest_version = manifest.get('latest_version', 'unknown')

    # Extract table names from migrations SQL for grants
    tables = sorted(set(re.findall(r'app_data\.([a-zA-Z_][a-zA-Z0-9_]*)', migrations_sql, re.IGNORECASE)))
    # Filter out alembic_version from grants (internal table)
    tables = [t for t in tables if t != 'alembic_version']

    if not tables:
        raise GenerationError(
            f"No table names extracted from {migrations_sql_path}. Check the SQL syntax."
        )

    # Generate grants for each table
    grants = []
    for table in tables:
        grants.append(f"""
-- Grant permissions for {table} table
GRANT SELECT ON TABLE app_data.{table} TO APPLICATION ROLE app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE app_data.{table} TO APPLICATION ROLE app_admin;""")

    full_content = migrations_sql + '\n' + '\n'.join(grants)

    # Read template and inject migrations SQL
    with open(template_path, 'r') as f:
        setup_content = f.read()

    if '{{MIGRATIONS_SQL}}' not in setup_content:
        raise GenerationError(
            f"Placeholder '{{{{MIGRATIONS_SQL}}}}' not found in {template_path}"
        )

    # Replace all placeholders
    setup_content = setup_content.replace('{{MIGRATIONS_SQL}}', full_content)
    setup_content = setup_content.replace('{{MIGRATIONS_COUNT}}', str(migrations_count))
    setup_content = setup_content.replace('{{LATEST_MIGRATION_VERSION}}', latest_version)

    if dry_run:
        print(f"[DRY-RUN] Would generate {output_path} with {len(tables)} tables: {', '.join(tables)}")
        print(f"          Migrations: {migrations_count}, Latest version: {latest_version}")
    else:
        with open(output_path, 'w') as f:
            f.write(setup_content)
        print(f"Generated {output_path} with {len(tables)} table definitions: {', '.join(tables)}")
        print(f"  Migrations count: {migrations_count}, Latest version: {latest_version}")


def main():
    parser = argparse.ArgumentParser(description='Generate application files from templates')
    parser.add_argument('--image-tag', required=True, help='Docker image tag (SHA)')
    parser.add_argument('--output-dir', default='app/src', help='Output directory')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be generated without writing files')

    args = parser.parse_args()

    # Ensure output directory exists (unless dry-run)
    output_dir = Path(args.output_dir)
    if not args.dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)

    # Common replacements (database, schema, and image repo are now hardcoded in templates)
    replacements = {
        'IMAGE_TAG': args.image_tag,
    }

    mode = "[DRY-RUN] " if args.dry_run else ""
    print(f"{mode}Generating files with:")
    print(f"  Image Tag: {args.image_tag}")
    print()

    try:
        # Generate manifest.yml
        generate_from_template(
            'templates/manifest_template.yml',
            str(output_dir / 'manifest.yml'),
            replacements,
            dry_run=args.dry_run
        )

        # Generate fullstack.yaml
        generate_from_template(
            'templates/fullstack_template.yaml',
            str(output_dir / 'fullstack.yaml'),
            replacements,
            dry_run=args.dry_run
        )

        # Generate migrations SQL from Alembic migrations
        print("Generating migrations SQL from Alembic...")
        import subprocess
        result = subprocess.run(
            ['python3', 'scripts/generate/generate_migrations_sql.py'],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            raise GenerationError(f"Failed to generate migrations SQL: {result.stderr}")
        print(result.stdout)

        # Generate setup.sql with migrations
        generate_setup_sql(
            'templates/setup_template.sql',
            'scripts/sql/migrations.sql',
            'scripts/sql/migrations_manifest.json',
            str(output_dir / 'setup.sql'),
            dry_run=args.dry_run
        )

        print()
        print(f"{mode}All files generated successfully!")

    except GenerationError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError as e:
        print(f"ERROR: File not found: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
