
use role accountadmin;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE naspcs_role;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO APPLICATION spcs_app_instance_test;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO APPLICATION spcs_app_instance_test;
