name: 'Docker Build and Push'
description: 'Build and push Docker image to Snowflake registry'

inputs:
  image-name:
    description: 'Name of the Docker image (e.g., eap_backend)'
    required: true
  context:
    description: 'Docker build context path (e.g., ./backend)'
    required: true
  snowflake-repo:
    description: 'Snowflake image repository URL'
    required: true
  private-key:
    description: 'Snowflake JWT private key (raw PEM content)'
    required: true
  account:
    description: 'Snowflake account identifier'
    required: true
  user:
    description: 'Snowflake user for deployment'
    required: true
  role:
    description: 'Snowflake role for deployment'
    required: true
  warehouse:
    description: 'Snowflake warehouse'
    required: true
  database:
    description: 'Snowflake database'
    required: true
  schema:
    description: 'Snowflake schema'
    required: true
  host:
    description: 'Snowflake host'
    required: true
  github-sha:
    description: 'GitHub SHA for tagging'
    required: true
  branch-tag:
    description: 'Branch name for additional tagging (e.g., qa, stable)'
    required: false
    default: ''

outputs:
  image-tag:
    description: 'The full image tag that was pushed'
    value: ${{ steps.meta.outputs.tag }}
  short-sha:
    description: 'The short SHA used for tagging'
    value: ${{ steps.meta.outputs.short_sha }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup Snowflake
      uses: ./.github/actions/snowflake-setup
      with:
        private-key: ${{ inputs.private-key }}
        account: ${{ inputs.account }}
        user: ${{ inputs.user }}
        role: ${{ inputs.role }}
        warehouse: ${{ inputs.warehouse }}
        database: ${{ inputs.database }}
        schema: ${{ inputs.schema }}
        host: ${{ inputs.host }}

    - name: Generate requirements.txt for backend
      if: ${{ inputs.image-name == 'eap_backend' }}
      shell: bash
      run: |
        echo "Generating requirements.txt from pyproject.toml..."
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.local/bin:$PATH"
        cd ${{ inputs.context }}
        uv export --no-hashes --no-dev -o requirements.txt
        echo "Generated requirements.txt with $(wc -l < requirements.txt) lines"

    - name: Generate image metadata
      id: meta
      shell: bash
      run: |
        SHORT_SHA=$(echo "${{ inputs.github-sha }}" | cut -c1-7)
        echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

        # Primary tag with SHA
        SHA_TAG="${{ inputs.snowflake-repo }}/${{ inputs.image-name }}:$SHORT_SHA"
        echo "tag=$SHA_TAG" >> $GITHUB_OUTPUT

        # Build tags list (SHA tag + optional branch tag)
        TAGS="$SHA_TAG"
        if [ -n "${{ inputs.branch-tag }}" ]; then
          BRANCH_TAG="${{ inputs.snowflake-repo }}/${{ inputs.image-name }}:${{ inputs.branch-tag }}"
          TAGS="$TAGS,$BRANCH_TAG"
          echo "branch_tag=$BRANCH_TAG" >> $GITHUB_OUTPUT
        fi
        echo "tags=$TAGS" >> $GITHUB_OUTPUT

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        cache-from: type=gha,scope=${{ inputs.image-name }}
        cache-to: type=gha,mode=max,scope=${{ inputs.image-name }}
