-- =============================================================================
-- DATABASE MIGRATIONS
-- Auto-generated from Alembic migrations - DO NOT EDIT MANUALLY
-- Source: backend/alembic/versions/
-- Generated by: scripts/generate/generate_migrations_sql.py
-- =============================================================================
{{MIGRATIONS_SQL}}
-- =============================================================================

-- =============================================================================
-- TABLE PERMISSIONS
-- =============================================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app_data TO APPLICATION ROLE app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app_data TO APPLICATION ROLE app_user;

-- =============================================================================
-- MIGRATION PROCEDURES
-- =============================================================================

-- All migrations above use idempotent SQL (IF NOT EXISTS / IF EXISTS) so they
-- can be safely re-run on upgrades. The alembic_version table tracks which
-- migrations have been applied.

-- Procedure to get migration status
CREATE OR REPLACE PROCEDURE app_data.get_migration_status()
    RETURNS STRING
    LANGUAGE SQL
AS
$$
DECLARE
    applied_count NUMBER;
    versions_list VARCHAR DEFAULT '';
BEGIN
    -- Count applied migrations
    SELECT COUNT(*) INTO :applied_count FROM app_data.alembic_version;

    -- Get list of applied versions
    SELECT LISTAGG(version_num, ', ') WITHIN GROUP (ORDER BY version_num)
    INTO :versions_list
    FROM app_data.alembic_version;

    IF (applied_count = 0) THEN
        RETURN 'No migrations applied yet';
    ELSE
        RETURN 'Applied migrations (' || :applied_count || '): ' || :versions_list;
    END IF;
END;
$$;

GRANT USAGE ON PROCEDURE app_data.get_migration_status() TO APPLICATION ROLE app_admin;

-- Procedure to get pending migrations count (migrations in code but not applied)
-- This uses the expected migrations from the manifest embedded at build time
CREATE OR REPLACE PROCEDURE app_data.get_pending_migrations_count()
    RETURNS NUMBER
    LANGUAGE SQL
AS
$$
DECLARE
    applied_count NUMBER;
    expected_count NUMBER DEFAULT {{MIGRATIONS_COUNT}};
BEGIN
    SELECT COUNT(*) INTO :applied_count FROM app_data.alembic_version;
    RETURN :expected_count - :applied_count;
END;
$$;

GRANT USAGE ON PROCEDURE app_data.get_pending_migrations_count() TO APPLICATION ROLE app_admin;

-- Procedure to verify all migrations are applied
-- Returns 'OK' if all migrations applied, otherwise lists missing ones
CREATE OR REPLACE PROCEDURE app_data.verify_migrations()
    RETURNS STRING
    LANGUAGE SQL
AS
$$
DECLARE
    applied_count NUMBER;
    expected_count NUMBER DEFAULT {{MIGRATIONS_COUNT}};
    latest_version VARCHAR DEFAULT '{{LATEST_MIGRATION_VERSION}}';
    has_latest NUMBER;
BEGIN
    SELECT COUNT(*) INTO :applied_count FROM app_data.alembic_version;
    SELECT COUNT(*) INTO :has_latest FROM app_data.alembic_version WHERE version_num = :latest_version;

    IF (:applied_count >= :expected_count AND :has_latest > 0) THEN
        RETURN 'OK - All ' || :expected_count || ' migrations applied. Latest: ' || :latest_version;
    ELSE
        RETURN 'PENDING - Applied ' || :applied_count || ' of ' || :expected_count ||
               ' migrations. Latest expected: ' || :latest_version;
    END IF;
END;
$$;

GRANT USAGE ON PROCEDURE app_data.verify_migrations() TO APPLICATION ROLE app_admin;
